News.WebApplication/Areas/Admin/Controllers/NewsGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using News.Models.DomainModels;
using News.Services.Repositories;

namespace News.WebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class NewsGroupController : Controller
    {
        private readonly INewsGroupRepository _newsGroupRepository;

        public NewsGroupController(INewsGroupRepository newsGroupRepository)
        {
            _newsGroupRepository = newsGroupRepository;
        }

        public async Task<IActionResult> NewsGroupList()
        {
            var newsGroups = await _newsGroupRepository.GetAllNewsGroupsAsync();
            return View(newsGroups);
        }

        #region Create

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsGroup newsGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(newsGroup);
            }

            await _newsGroupRepository.InsertNewsGroupAsync(newsGroup);

            TempData["Success"] = $"دسته بندی {newsGroup.GroupTitle} با موفقیت افزوده شد";
            return RedirectToAction("NewsGroupList");
        }

        #endregion

        #region Edit

        public async Task<IActionResult> Edit(int id = 0)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var newsGroup = await _newsGroupRepository.GetNewsGroupByIdAsync(id);

            if (newsGroup == null)
            {
                return BadRequest();
            }

            return View(newsGroup);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(NewsGroup newsGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(newsGroup);
            }

            await _newsGroupRepository.UpdateNewsGroupAsync(newsGroup);
            TempData["Success"] = "دسته بندی خبر با موفقیت ویرایش یافت";
            return RedirectToAction("NewsGroupList");
        }

        #endregion

        #region Delete

        [HttpPost]
        public async Task<IActionResult> Delete(int id = 0)
        {
            if (id == 0)
            {
                return StatusCode(404);
            }

            var isSucceeded = await _newsGroupRepository.DeleteNewsGroupAsync(id);

            if (!isSucceeded)
            {
                return StatusCode(403);
            }

            return StatusCode(200);
        }

        #endregion

    }
}

News.WebApplication/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using News.Models.ViewModels;
using News.Models.MetaModels;
using News.Services.Repositories;

namespace News.WebApplication.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsRepository _newsRepository;

        public NewsController(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }

        [Route("News/{newsId}")]
        public async Task<IActionResult> ShowNews(int newsId)
        {
            var news = await _newsRepository.GetNewsByIdAsync(newsId);
            if (news == null)
            {
                return NotFound();
            }
            news.VisitCount += 1;
            await _newsRepository.UpdateNewsAsync(news);
            return View(news);
        }

        [Route("Group/{groupId}/{title}")]
        public async Task<IActionResult> ShowNewsByGroupId(int groupId, string title, int? page)
        {
            var news = await _newsRepository.GetNewsByGroupIdAsync(groupId);
                
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            ViewData["GroupTitle"] = title;

            return View(PaginatedList<Models.DomainModels.News>.Create(news, pageNumber, pageSize));
        }

        [Route("Search")]
        public async Task<IActionResult> Search(string q)
        {
            var result = new SearchViewModel()
            {
                Query = q,
                Result = await _newsRepository.SearchAsync(q)
            };
            return View(result);
        }

        public async Task<IActionResult> Archive(int? page)
        {
            var news = await _newsRepository.GetAllNewsAsync();

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(PaginatedList<Models.DomainModels.News>.Create(news, pageNumber, pageSize));
        }
    }
}

News.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title> @ViewData["Title"] </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link href="/plugins/toastr/toastr.min.css" rel="stylesheet" type="text/css" />
    <script src="/js/jquery.min.js"></script>
    <script src="/js/modernizr.js"></script>
    @RenderSection("Head", required: false)
</head>
<body>
    <!-- Top Menu -->
    <div class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-5">
                    <ul>
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i></a></li>
                        <li><a href=""><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-7">
                    <span>امروز : @DateTime.Now.ToPersianDigitalDateTimeString()</span>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Menu -->
    <!-- header -->
    <header class="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a href="/" class="logo"><img src="/img/logo-new.png" class="header-logo" alt="" title=""></a>
                    <div class="left-side">
                        <h1><a href="/">سایت خبری خاص</a></h1>
                        <h2> پایگاه اطلاع رسانی و خبری</h2>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <form action="/Search" method="get" class="border-radius">
                        <input class="border-radius" name="q" required="" type="text" placeholder=" جستجو کنید ... ">
                        <button><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- End Header -->
    <!-- menu -->
    <nav class="main-menu">
        <div class="container">
            <span><i class="fa fa-th-list"></i></span>
            <partial name="_ShowGroupsInMenu" />
        </div>
    </nav>
    <!-- End menu -->

    <div class="container margin-top-30">
        <div class="row">
            <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">
                <!-- admin panel -->
                @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                {
                    <section class="category-section border-radius">
                        <header><i class="fa fa-newspaper-o"></i> <h3> مدیریت </h3></header>
                        <ul>
                            <li>
                                <a asp-area="Admin" asp-controller="News" asp-action="NewsList">
                                    مدیریت اخبار
                                </a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="News" asp-action="Create">
                                    ایجاد خبر جدید
                                </a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="NewsGroup" asp-action="NewsGroupList">
                                    مدیریت دسته بندی اخبار
                                </a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="NewsGroup" asp-action="Create">
                                    ایجاد دسته بندی جدید
                                </a>
                            </li>
                        </ul>
                    </section>
                }
                @await Component.InvokeAsync("ShowGroupsComponent")
                <!-- most views news -->
                @await Component.InvokeAsync("ShowTopNewsComponent")
                <!-- end most views news -->
            </aside>
            <div class="col-md-8 col-sm-12 col-xs-12 ">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <section class="access-links">
                        <header> دسترسی سریع </header>
                        <ul>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                            <li><a href=""> پیوندهای سایت </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
                    <div class="socials">
                        <span> شبکه های اجتماعی  سایت</span>
                        <a href=""><i class="fa fa-facebook"></i></a>
                        <a href=""><i class="fa fa-twitter"></i></a>
                        <a href=""><i class="fa fa-paper-plane"></i></a>
                        <a href=""><i class="fa fa-google-plus"></i></a>
                        <div class="clearfix"></div>
                    </div>
                    <p>
                        تمامی حقوق مادی و معنوی این طرح متعلق به مسعود خدادادی می باشد و کپی برداری از این طرح غیر اخلاقی می باشد.
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/owl.carousel.js"></script>
    <script src="/js/script.js"></script>
    <script src="/plugins/toastr/toastr.min.js"></script>
    <script>
    $(function() {
        if ("@TempData["Error"]" !== "")
        {
            toastr["error"]("@TempData["Error"]", "خطا");

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-bottom-left",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "500",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        }
        if ("@TempData["Success"]" !== "") {
            toastr["success"]("@TempData["Success"]", "موفق");

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "500",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        }
    });
    </script>
    @RenderSection("Scripts", false)
</body>
</html>

News.WebApplication/Views/Shared/_ShowGroupsInMenu.cshtml
@inject INewsGroupRepository GroupRepository

@{
    var listGroups = await GroupRepository.GetListGroupsAsync();
}
<ul>
    <li><a asp-area="" asp-controller="Home" asp-action="Index"> صفحه اصلی </a></li>
    <li>
        <span>گروه های خبری</span>
        <ul>
            @foreach (var item in listGroups)
            {
                <li>
                    <a asp-controller="News"
                       asp-action="ShowNewsByGroupId"
                       asp-route-groupId="@item.GroupId"
                       asp-route-title="@item.GroupTitle">
                        @item.GroupTitle
                    </a>
                </li>
            }
        </ul>
    </li>
    @if (User.Identity.IsAuthenticated)
    {

        <li class="pull-left">
            <b><a asp-area="" asp-controller="Account" asp-action="LogOut"><span class="fa fa-power-off"></span>&nbsp;خروج</a></b>
        </li>
        <li class="pull-left">
            <a asp-area="" asp-controller="Account" asp-action="EditProfile">مشاهده پروفایل </a>
        </li>
    }
    else
    {
        <li class="pull-left">
            <a asp-area="" asp-controller="Account" asp-action="Login">ورود</a>
        </li>
        <li class="pull-left">
            <a asp-area="" asp-controller="Account" asp-action="Register">ثبت نام</a>
        </li>
    }
</ul>