News.WebApplication/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using News.Models.MetaModels;
using News.Models.ViewModels;
using News.Services.Repositories;

namespace News.WebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class NewsController : Controller
    {
        private readonly INewsRepository _newsRepository;
        private readonly INewsGroupRepository _newsGroupRepository;

        public NewsController(INewsRepository newsRepository, INewsGroupRepository newsGroupRepository)
        {
            _newsRepository = newsRepository;
            _newsGroupRepository = newsGroupRepository;
        }

        public async Task<IActionResult> NewsList(int? page)
        {
            var allNews = await _newsRepository.GetAllNewsAsync();
            List<NewsListViewModel> newsModel = new List<NewsListViewModel>();
            foreach (var news in allNews)
            {
                var newsList = new NewsListViewModel()
                {
                    Id = news.Id,
                    CreateDate = news.CreateDate,
                    ImageName = news.ImageName,
                    Title = news.Title,
                    VisitCount = news.VisitCount,
                    NewsGroupId = news.NewsGroupId
                };
                newsModel.Add(newsList);
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(PaginatedList<NewsListViewModel>.Create(newsModel, pageNumber, pageSize));
        }

        #region Create

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Models.DomainModels.News news, IFormFile imageFile, string newsGroupName)
        {
            if (!ModelState.IsValid)
            {
                return View(news);
            }

            if (imageFile == null)
            {
                ModelState.AddModelError("ImageName", "عکسی برای خبر آپلود کنید");
                return View(news);
            }

            if (imageFile.Length > 500000)
            {
                ModelState.AddModelError("ImageName", "حجم عکس بیش از ۵۰۰ کیلوبایت می باشد");
                return View(news);
            }

            var newsGroup = await _newsGroupRepository.GetNewsGroupByNameAsync(newsGroupName);

            if (newsGroup == null)
            {
                ModelState.AddModelError("NewsGroup.GroupTitle", "گروه خبری موجود نمی باشد");
                return View(news);
            }

            //var rnd = new Random();
            //news.Id = rnd.Next();
            news.CreateDate = DateTime.Now;
            news.ImageName = Guid.NewGuid() + Path.GetExtension(imageFile.FileName);
            news.VisitCount = 0;
            news.NewsGroupId = newsGroup.Id;
            //news.NewsGroup = newsGroup;

            try
            {
                string savePath = Path.Combine(
                    Directory.GetCurrentDirectory(), "wwwroot/img/news-images",
                    news.ImageName
                );
                await using var stream = new FileStream(savePath, FileMode.Create);
                await imageFile.CopyToAsync(stream);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            await _newsRepository.InsertNewsAsync(news);

            TempData["Success"] = "خبر با موفقیت افزوده شد";
            return RedirectToAction("NewsList", "News");
        }

        #endregion

        #region Delete

        [HttpPost]
        public async Task<IActionResult> Delete(int id = 0)
        {
            if (id == 0)
            {
                return StatusCode(404);
            }

            var news = await _newsRepository.GetNewsByIdAsync(id);

            if (news == null)
            {
                return StatusCode(404);
            }

            var oldImage = news.ImageName;
            string oldImagePath = Path.Combine(Directory.GetCurrentDirectory(),
                "wwwroot/img/news-images/", oldImage);
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            else
            {
                //_logger.LogError($"The image path cannot be found. Path = {oldImagePath}");
            }

            await _newsRepository.DeleteNewsAsync(news);

            return StatusCode(200);
        }

        #endregion

        #region Edit

        public async Task<IActionResult> Edit(int id)
        {
            var news = await _newsRepository.GetNewsByIdAsync(id);

            if (news == null)
            {
                return NotFound();
            }

            ViewBag.GroupId = new SelectList(await _newsGroupRepository.GetAllNewsGroupsAsync(), "Id", "GroupTitle", news.NewsGroupId);

            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Models.DomainModels.News news, IFormFile imageFile)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.GroupId = new SelectList(await _newsGroupRepository.GetAllNewsGroupsAsync(), "Id", "GroupTitle", news.NewsGroupId);
                return View(news);
            }

            try
            {
                if (imageFile != null)
                {
                    var oldImage = news.ImageName;
                    string oldImagePath = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot/img/news-images/", oldImage);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                    else
                    {
                        //_logger.LogError($"The image path cannot be found. Path = {oldImagePath}");
                    }

                    news.ImageName = Guid.NewGuid() + Path.GetExtension(imageFile.FileName);

                    string savePath = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot/img/news-images", news.ImageName
                    );
                    using (var stream = new FileStream(savePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                }

                await _newsRepository.UpdateNewsAsync(news);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!(await NewsExists(news.Id)))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            TempData["Success"] = "خبر با موفقیت ثبت شد";

            return RedirectToAction("NewsList", "News");
        }

        private async Task<bool> NewsExists(int id)
        {
            return await _newsRepository.NewsExistsAsync(id);
        }

        #endregion
    }
}

News.WebApplication/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using News.Models.DomainModels;
using News.Services.Repositories;

namespace News.WebApplication.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _commentRepository;
        private readonly IUserRepository _userRepository;
        private readonly INewsRepository _newsRepository;

        public CommentController(ICommentRepository commentRepository, IUserRepository userRepository, INewsRepository newsRepository)
        {
            _commentRepository = commentRepository;
            _userRepository = userRepository;
            _newsRepository = newsRepository;
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(string content, string userEmail, int newsId = 0)
        {
            if (newsId == 0)
            {
                return BadRequest();
            }

            var news = await _newsRepository.GetNewsByIdAsync(newsId);

            if (news == null)
            {
                return BadRequest();
            }

            var user = await _userRepository.GetUserByEmailAsync(userEmail);

            if (user == null)
            {
                return StatusCode(403);
            }

            var comment = new Comment()
            {
                Content = content,
                DateTime = DateTime.Now,
                IsConfirmed = true,
                NewsId = newsId,
                UserId = user.Id
            };
            await _commentRepository.AddCommentForNewsAsync(comment, user, news);

            TempData["Success"] = "نظر شما با موفقیت افزوده شد";

            return RedirectToAction("ShowNews", "News", new {newsId});
        }
    }
}

News.WebApplication/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using News.Models.ViewModels;
using News.Models.MetaModels;
using News.Services.Repositories;

namespace News.WebApplication.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsRepository _newsRepository;

        public NewsController(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }

        [Route("News/{newsId}")]
        public async Task<IActionResult> ShowNews(int newsId)
        {
            var news = await _newsRepository.GetNewsByIdAsync(newsId);
            if (news == null)
            {
                return NotFound();
            }
            news.VisitCount += 1;
            await _newsRepository.UpdateNewsAsync(news);
            return View(news);
        }

        [Route("Group/{groupId}/{title}")]
        public async Task<IActionResult> ShowNewsByGroupId(int groupId, string title, int? page)
        {
            var news = await _newsRepository.GetNewsByGroupIdAsync(groupId);
                
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            ViewData["GroupTitle"] = title;

            return View(PaginatedList<Models.DomainModels.News>.Create(news, pageNumber, pageSize));
        }

        [Route("Search")]
        public async Task<IActionResult> Search(string q)
        {
            var result = new SearchViewModel()
            {
                Query = q,
                Result = await _newsRepository.SearchAsync(q)
            };
            return View(result);
        }

        public async Task<IActionResult> Archive(int? page)
        {
            var news = await _newsRepository.GetAllNewsAsync();

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(PaginatedList<Models.DomainModels.News>.Create(news, pageNumber, pageSize));
        }
    }
}

News.WebApplication/Views/News/Archive.cshtml
@model PaginatedList<News>
@{
    ViewData["Title"] = "آرشیو اخبار";
}

<section class="last-news-section border-radius">
    <header><i class="icons icon-doc-2"></i>  <h3>آرشیو اخرین اخبار</h3> </header>
    <ul>
        @foreach (var item in Model)
        {
            <li>
                <img class="border-radius" src="/img/news-images/@item.ImageName">
                <h2> <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id"> @item.Title </a></h2>
                <p>
                    @item.ShortDescription
                </p>
                <span class="date-publish"><i class="fa fa-calendar"></i> انتشار : @item.CreateDate.ToPersianDateString() </span>
                <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id" class="more-link"><i class="icons icon-more"></i></a>
            </li>
        }
    </ul>
</section>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";


    <div class="text-center">
        <a asp-controller="News" asp-action="Archive"
           asp-route-page="@(Model.PageIndex - 1)"
           class="btn btn-default @prevDisabled">
            قبلی
        </a>
        <a asp-controller="News" asp-action="Archive"
           asp-route-page="@(Model.PageIndex + 1)"
           class="btn btn-default @nextDisabled">
            بعدی
        </a>
    </div>
}

News.WebApplication/Views/News/Search.cshtml
@model SearchViewModel
@{
    ViewData["Title"] = "جستجو";
}

<section class="last-news-section border-radius">
    <header><i class="icons icon-doc-2"></i>  <h3>نتایج یافت شده برای عبارت "@Model.Query"</h3> </header>
    <ul>
        @if (Model.Result.Any())
        {
            foreach (var item in Model.Result)
            {
                <li>
                    <img class="border-radius" src="/img/news-images/@item.ImageName">
                    <h2> <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id"> @item.Title </a></h2>
                    <p>
                        @item.ShortDescription
                    </p>
                    <span class="date-publish"><i class="fa fa-calendar"></i> انتشار : @item.CreateDate.ToPersianDateTime() </span>
                    <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id" class="more-link"><i class="icons icon-more"></i></a>
                </li>
            }
        }
        else
        {
            <div class="margin-top-down text-center">
                موردی یافت نشد
            </div>
        }

    </ul>
</section>

News.WebApplication/Views/News/ShowNews.cshtml
@using News.Utilities.DateTimeUtility
@inject IUserRepository UserRepository
@inject INewsGroupRepository NewsGroupRepository
@inject ICommentRepository CommentRepository
@model News
@{
    ViewData["Title"] = Model.Title;
    var newsGroup = await NewsGroupRepository.GetNewsGroupByIdAsync(Model.NewsGroupId);
}



<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">خانه </a></li>
    <li class="breadcrumb-item"><a href="/">اخبار </a></li>
    <li class="breadcrumb-item"><a href="/Group/@Model.NewsGroupId/@newsGroup.GroupTitle">@newsGroup.GroupTitle  </a></li>
    <li class="breadcrumb-item active">@Model.Title </li>
</ul>

<section class="single-news border-radius">
    <header><h2> @Model.Title </h2> <span> <i class="fa fa-calendar"></i>  انتشار : @Model.CreateDate.ToPersianDateString()</span></header>
    <article>
        <p>
            @Model.ShortDescription
        </p>

        @if (Model.ImageName != null)
        {
            <div>
                <img src="/img/news-images/@Model.ImageName" style="max-width: 600px;" alt="@Model.Title" class="thumbnail" />
            </div>
        }

        <p>
            @Model.Description
        </p>
    </article>
</section>

<div class="keywords border-radius">
    @foreach (var item in Model.Tags.Split(','))
    {
        <a href="/Search?q=@item"> @item </a>
    }
</div>
<br />
<section class="category-section border-radius">
    <header><i class="fa fa-comment-o"></i> <h3> نظرات </h3></header>
    <div class="container-fluid">
        @{
            var comments = await CommentRepository.GetAllCommentsByNewsIdAsync(Model.Id);
            if (comments.Any())
            {
                foreach (var comment in comments)
                {
                    var user = await UserRepository.GetUserByIdAsync(comment.UserId);
                    <div class="row p-5">
                        <div class="comment">
                            <img src="/img/avatar-cm.png" alt="" class="comment-avatar">
                            <div class="comment-body">
                                <div class="comment-text">
                                    <div class="comment-header">
                                        <a href="#" title="">@user.FullName </a><span>&nbsp; @comment.DateTime.ElapsedTime()</span>
                                    </div>
                                    @comment.Content
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="text-center p-5">
                    هیچ نظری وجود ندارد.
                </div>
            }
        }
    </div>
</section>
<div class="text-center">
    @if (!User.Identity.IsAuthenticated)
    {
        <div class="m-t-30 text-center">
            برای ثبت نظر باید <a style="color:#009dad" asp-controller="Account" asp-action="Login">وارد</a> شوید
        </div>
    }
    else
    {
        <br />
        <form method="post" class="card-box" asp-controller="Comment" asp-action="AddComment">
            <input type="hidden" name="userEmail" value="@User.Identity.Name" />
            <input type="hidden" name="newsId" value="@Model.Id" />
            <div class="row">
                <div class="col-md-12">
                    <label for="comment-content" class="control-label pull-right">
                        نظر خود را بنویسید
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <input type="text" class="form-control" id="comment-content" name="content" required=""/>
                </div>
                <div class="col-md-2 p-t-10 text-left">
                    <input type="submit" class="btn btn-sm btn-primary waves-effect waves-light" value="ارسال"/>
                </div>
            </div>
        </form>
    }
</div>

News.WebApplication/Views/News/ShowNewsByGroupId.cshtml
@model PaginatedList<News>
@{
    ViewData["Title"] = " خبر های گروه " + ViewData["GroupTitle"];
}
<section class="last-news-section border-radius">
    <header><i class="icons icon-doc-2"></i>  <h3>آخرین اخبار ارسالی گروه @ViewData["GroupTitle"]</h3> </header>
    <ul>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <li>
                    <img class="border-radius" src="/img/news-images/@item.ImageName">
                    <h2> <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id"> @item.Title </a></h2>
                    <p>
                        @item.ShortDescription
                    </p>
                    <span class="date-publish"><i class="fa fa-calendar"></i> انتشار : @item.CreateDate.ToPersianDateString() </span>
                    <a asp-controller="News" asp-action="ShowNews" asp-route-newsId="@item.Id" class="more-link"><i class="icons icon-more"></i></a>
                </li>
            }
        }
        else
        {
            <div class="margin-top-down text-center">
                موردی یافت نشد
            </div>
        }
    </ul>
</section>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";


    <div class="text-center">
        <a asp-controller="News" asp-action="Archive"
           asp-route-page="@(Model.PageIndex - 1)"
           class="btn btn-default @prevDisabled">
            قبلی
        </a>
        <a asp-controller="News" asp-action="Archive"
           asp-route-page="@(Model.PageIndex + 1)"
           class="btn btn-default @nextDisabled">
            بعدی
        </a>
    </div>
}